# Generated by Django 5.0.4 on 2026-05-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptercomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='mangacomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at']},
        ),
    ]
